version: "3.4"

services:
  database:
    image: "mongo:4.4.1"
    ports:
      - 27017:27017
    volumes:
      - ./backend/data:/data/db
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    ports:
      - 8081:8081
    volumes:
      - ./backend:/home/node/app
      - ./backend/node_modules:/home/node/app/node_modules
    networks:
      - app-network
    depends_on:
      - database
    command: "npm run dev"

  frontend:
    build:
      context: ./frontend
      target: build
    restart: unless-stopped
    env_file: ./frontend/.env
    ports:
      - 80:80
      - 35729:35729 #livereload
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    networks:
      - app-network
    depends_on:
      - backend
    command: "npm run dev"

networks:
  app-network:
    driver: bridge
